# Generated by Django 5.0.1 on 2024-02-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_place_tbl_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newUser',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
