# Generated by Django 5.0.1 on 2024-02-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newUser',
        ),
    ]
