# Generated by Django 5.0.1 on 2024-02-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
    ]
