# Generated by Django 5.0.2 on 2024-02-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
    ]
