# Generated by Django 5.0.1 on 2024-02-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_delete_tbl_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_material')),
            ],
        ),
    ]
