# Generated by Django 5.0.2 on 2024-02-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_designerwork',
            name='designerwork_rate',
            field=models.IntegerField(),
        ),
    ]
