# Generated by Django 5.0.1 on 2024-02-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0002_alter_tbl_designerwork_designerwork_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_designerwork',
        ),
    ]
