# Generated by Django 5.0.1 on 2024-02-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_designerwork',
        ),
    ]
