# Generated by Django 5.0.1 on 2024-02-24 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0007_alter_tbl_designerwork_designerwork_duration'),
        ('Guest', '0006_delete_tbl_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_designerwork',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_designer'),
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_file', models.FileField(upload_to='Assets/DesignerGallery/')),
                ('gallery_caption', models.TextField(max_length=50)),
                ('designerwork_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_designer')),
            ],
        ),
    ]
