# Generated by Django 5.0.1 on 2024-02-24 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0008_alter_tbl_designerwork_designer_tbl_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_gallery',
            name='designerwork_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Designer.tbl_designerwork'),
        ),
    ]
