# Generated by Django 5.0.2 on 2024-03-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Designer', '0009_alter_tbl_gallery_designerwork_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_designerwork',
            name='designerwork_duration',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='tbl_designerwork',
            name='designerwork_rate',
            field=models.IntegerField(default='0'),
        ),
    ]
