# Generated by Django 5.0.1 on 2024-02-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_newuser'),
        ('Guest', '0003_delete_tbl_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_name', models.CharField(max_length=50)),
                ('designer_gender', models.CharField(max_length=50)),
                ('designer_contact', models.CharField(max_length=50)),
                ('designer_email', models.CharField(max_length=50)),
                ('designer_password', models.CharField(max_length=50)),
                ('designer_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('designer_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('designer_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
