# Generated by Django 5.0.1 on 2024-02-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_designer',
            name='designer_photo',
            field=models.FileField(upload_to='Assets/DesignerPhoto/'),
        ),
        migrations.AlterField(
            model_name='tbl_designer',
            name='designer_proof',
            field=models.FileField(upload_to='Assets/DesignerProof/'),
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=500)),
                ('complaint_details', models.CharField(max_length=500)),
                ('complaint_postdate', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=500)),
                ('complaint_replydate', models.DateField()),
                ('complaint_status', models.IntegerField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
