# Generated by Django 5.0.1 on 2024-02-20 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_designer_designer_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
