# Generated by Django 5.0.1 on 2024-02-20 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_delete_tbl_complaint'),
        ('User', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_subject', models.CharField(max_length=500)),
                ('feedback_details', models.CharField(max_length=500)),
                ('feedback_postdate', models.DateField(auto_now_add=True)),
                ('feedback_status', models.IntegerField(default='0')),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_designer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
