# Generated by Django 5.0.2 on 2024-03-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(max_length=200)),
                ('Rating_details', models.IntegerField(default='0')),
                ('Comment_details', models.CharField(max_length=200)),
            ],
        ),
    ]
